# Generated by Django 5.0.6 on 2024-08-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_leave_availability_initial_permission_remaining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='from_Date',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='to_Date',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='total_leave',
        ),
    ]
