# Generated by Django 5.0.6 on 2024-08-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0036_remove_permission_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='On_date',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='leave_type',
            field=models.CharField(default='Permission', max_length=50),
        ),
    ]
