# Generated by Django 5.0.6 on 2024-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_permission_on_date_alter_permission_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHProof',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('leave_type', models.CharField(default='CHProof', max_length=50)),
                ('date_Applied', models.DateTimeField(max_length=50)),
                ('On_date', models.CharField(default='-', max_length=50)),
                ('in_Time', models.CharField(max_length=50)),
                ('Out_Time', models.CharField(max_length=50)),
                ('status', models.CharField(default='Reviewing', max_length=50)),
                ('unique_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='leave_documents/')),
            ],
        ),
    ]
