# Generated by Django 5.0.6 on 2024-08-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0038_chproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chproof',
            name='On_date',
            field=models.CharField(max_length=50),
        ),
    ]
